version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: my-laravel-app
    container_name: my-laravel-container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    networks:
      - my-laravel-app-network
    volumes:
      - ./src/:/var/www/html

    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: my-mysql-container
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: example
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - my-laravel-app-network
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33060:3306"

networks:
  my-laravel-app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
